### ISSUE TITLE
Errors at start 1.4.10

### ISSUE THREAD

**Issue by H4Mm3r** [minecraftabnormals/Upgrade-Aquatic#101]
Hello, there is a lot of errors at start, known issue ?

[12Apr2020 19:53:28.886] [Server thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, AutoRegLib-1.4-35.jar, atmospheric-1.14.4-1.1.2.jar, BetterCaves-1.14.4-1.1.1.jar, BiomesOPlenty-1.14.4-9.0.0.262-universal.jar, BasicNetherOres-1.14.4-3.2.4.jar, Explorercraft-1.14.4-3.2.7.jar, forge-1.14.4-28.2.3-universal.jar, mysticallib-1.14.4-1.16.1.jar, Quark-r2.0-212.jar, rys-0.1.18.jar, SaveMyStronghold-1.14.4-1.0.0.jar, swampexpansion-1.4.9.jar, traverse-1.14.4-2.0.3.jar, Upgrade-Aquatic-1.14.4-v1.4.10.jar
[12Apr2020 19:53:29.222] [Server-Worker-3/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read item tag list minecraft:flower_pots from minecraft:tags/items/flower_pots.json in data pack Default
com.google.gson.JsonParseException: Unknown value 'upgrade_aquatic:potted_pickerelweed_blue'
        at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
        at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
        at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
[12Apr2020 19:53:29.224] [Server-Worker-3/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read item tag list minecraft:flower_pots from minecraft:tags/items/flower_pots.json in data pack Upgrade-Aquatic-1.14.4-v1.4.10.jar
com.google.gson.JsonParseException: Unknown value 'upgrade_aquatic:potted_pickerelweed_blue'
        at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
        at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
        at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
[12Apr2020 19:53:29.285] [Server-Worker-4/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read block tag list minecraft:stairs from minecraft:tags/blocks/stairs.json in data pack Upgrade-Aquatic-1.14.4-v1.4.10.jar
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913) ~[server-1.14.4-extra-stable.jar:?]
        at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?]
        at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:533) ~[?:?]
        at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:93) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
[12Apr2020 19:53:29.285] [Server-Worker-3/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read item tag list minecraft:stairs from minecraft:tags/items/stairs.json in data pack Upgrade-Aquatic-1.14.4-v1.4.10.jar
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913) ~[server-1.14.4-extra-stable.jar:?]
        at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?]
        at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:533) ~[?:?]
        at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:93) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
[12Apr2020 19:53:29.301] [Server-Worker-3/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read item tag list forge:supports_conduit from forge:tags/items/supports_conduit.json in data pack Upgrade-Aquatic-1.14.4-v1.4.10.jar
com.google.gson.JsonParseException: Unknown value 'upgrade_aquatic:prismarine_coral_wall_fan'
        at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
        at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
        at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
[12Apr2020 19:53:30.068] [Server thread/INFO] [net.minecraft.item.crafting.RecipeManager/]: Skipping loading recipe minecraft:red_wool as it's conditions were not met
[12Apr2020 19:53:30.071] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_vertical_slab_stonecutting
com.google.gson.JsonSyntaxException: Unknown item 'upgrade_aquatic:ochre_kelpy_stone_bricks'
        at net.minecraft.item.crafting.Ingredient.lambda$deserializeItemList$12(Ingredient.java:214) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
        at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:213) ~[?:?]
        at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[?:?]
        at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[?:?]
        at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:187) ~[?:?]
        at net.minecraft.item.crafting.SingleItemRecipe$Serializer.func_199425_a_(SingleItemRecipe.java:76) ~[?:?]
        at net.minecraft.item.crafting.SingleItemRecipe$Serializer.func_199425_a_(SingleItemRecipe.java:63) ~[?:?]
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?]
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) ~[?:?]
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?]
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
        at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1432) [?:?]
        at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:436) [?:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:351) [?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [?:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
 and a lot of others

[12Apr2020 19:53:30.225] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_wall
[12Apr2020 19:53:30.227] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_stairs_stonecutting
[12Apr2020 19:53:30.237] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_stairs
com.google.gson.JsonSyntaxException: Unknown item 'upgrade_aquatic:kelpy_stone_bricks'

**Comment by H4Mm3r** [comment]
Full lit 👍 
[12Apr2020 20:18:47.044] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_vertical_slab_stonecutting
[12Apr2020 20:18:47.068] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:polar_kelpy_stone_brick_wall
[12Apr2020 20:18:47.087] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:polar_kelpy_stone_brick_slab_stonecutting
[12Apr2020 20:18:47.089] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:polar_kelpy_stone_brick_wall_stonecutting
[12Apr2020 20:18:47.100] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:dead_acan_coral_block
[12Apr2020 20:18:47.119] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_slab
[12Apr2020 20:18:47.120] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_slab
[12Apr2020 20:18:47.140] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_wall
[12Apr2020 20:18:47.151] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:polar_kelpy_stone_brick_stairs_stonecutting
[12Apr2020 20:18:47.153] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:polar_kelpy_stone_brick_stairs
[12Apr2020 20:18:47.155] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:block_bubble
[12Apr2020 20:18:47.168] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_wall
[12Apr2020 20:18:47.170] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_stairs_stonecutting
[12Apr2020 20:18:47.182] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_stairs
[12Apr2020 20:18:47.202] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_stairs_stonecutting
[12Apr2020 20:18:47.207] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_stairs
[12Apr2020 20:18:47.209] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_stairs_stonecutting
[12Apr2020 20:18:47.213] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_vertical_slab_stonecutting
[12Apr2020 20:18:47.223] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_vertical_slab_stonecutting
[12Apr2020 20:18:47.229] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_slab
[12Apr2020 20:18:47.231] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_slab
[12Apr2020 20:18:47.233] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_stairs_stonecutting
[12Apr2020 20:18:47.288] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_stairs
[12Apr2020 20:18:47.292] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_slab_stonecutting
[12Apr2020 20:18:47.297] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:polar_kelpy_stone_brick_slab
[12Apr2020 20:18:47.299] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_wall_stonecutting
[12Apr2020 20:18:47.305] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:polar_kelpy_stone_brick_vertical_slab_stonecutting
[12Apr2020 20:18:47.306] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_wall
[12Apr2020 20:18:47.307] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:kelpy_stone_brick_vertical_slab_stonecutting
[12Apr2020 20:18:47.309] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_stairs
[12Apr2020 20:18:47.309] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_slab_stonecutting
[12Apr2020 20:18:47.310] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_wall
[12Apr2020 20:18:47.312] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_wall_stonecutting
[12Apr2020 20:18:47.313] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:thorny_kelpy_stone_brick_wall_stonecutting
[12Apr2020 20:18:47.314] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:tongue_kelpy_stone_brick_slab_stonecutting
[12Apr2020 20:18:47.318] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_wall_stonecutting
[12Apr2020 20:18:47.332] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe upgrade_aquatic:ochre_kelpy_stone_brick_slab_stonecutting

**Comment by SmellyModder** [comment]
Any issues in the 1.14.4 versions will no longer be fixed unfortunately, that's just how we do things. These errors shouldn't affect the gameplay in any way, they'll just be annoying in the logs.

**Comment by H4Mm3r** [comment]
Thanks for the answer
