### ISSUE TITLE
Upgrade Aquatic triggers "safe mode" 

### ISSUE THREAD

**Issue by FluffiKiki** [minecraftabnormals/Upgrade-Aquatic#400]
Mod version 6.0.0, Forge 47.2.20, Minecraft 1.20.1

Whenever Upgrade Aquatic is installed, it triggers the "safe mode" or go back option when loading worlds. In the previous and beta versions, it had issues with loading with Create. Is this still an issue or is it something else? Thanks!

**Comment by bageldotjpg** [comment]
provide your latest.log

**Comment by FluffiKiki** [comment]
[latest.log](https://github.com/team-abnormals/upgrade-aquatic/files/15158266/latest.log)

**Comment by ExpensiveKoala** [comment]
Caused by: java.lang.IllegalStateException: Can't modify the empty stack.
	at net.minecraftforge.fluids.FluidStack.setTag(FluidStack.java:200) ~[forge-1.20.1-47.2.20-universal.jar%23533!/:?]
	at net.minecraftforge.fluids.FluidStack.getOrCreateTag(FluidStack.java:207) ~[forge-1.20.1-47.2.20-universal.jar%23533!/:?]
	at com.simibubi.create.foundation.fluid.FluidIngredient$FluidStackIngredient.readInternal(FluidIngredient.java:182) ~[create-1.20.1-0.5.1.f.jar%23373!/:0.5.1.f]
	at com.simibubi.create.foundation.fluid.FluidIngredient.deserialize(FluidIngredient.java:131) ~[create-1.20.1-0.5.1.f.jar%23373!/:0.5.1.f]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:64) ~[create-1.20.1-0.5.1.f.jar%23373!/:0.5.1.f]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-1.20.1-0.5.1.f.jar%23373!/:0.5.1.f]

The issue is with create. Perhaps there is a recipe create is loading that has a fluid as an ingredient. It is attempting to call setTag on a fluidstack whose fluid does not exist.
