### ISSUE TITLE
java.lang.RuntimeException: Attempted to load class com/teamabnormals/upgrade_aquatic/api/endimator/ControlledEndimation

### ISSUE THREAD

**Issue by SDUBZ** [minecraftabnormals/Upgrade-Aquatic#57]
forge-1.14.4-28.1.107
Upgrade-Aquatic-1.14.4-v1.4.2
[Attempted to load class com/teamabnormals/upgrade_aquatic/api/endimator/ControlledEndimation for invalid dist DEDICATED_SERVER]
java.lang.RuntimeException: Attempted to load class com/teamabnormals/upgrade_aquatic/api/endimator/ControlledEndimation for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.14.4-28.1.107.jar:28.1] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) ~[modlauncher-4.1.0.jar:4.1.0+62+5bfa59b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222] {}
        at com.teamabnormals.upgrade_aquatic.common.entities.thrasher.EntityThrasher.<init>(EntityThrasher.java:74) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:412) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.silentchaos512.gems.lib.soul.Soul$Events.canHaveSoulGem(Soul.java:206) [?:3.4.7+80] {re:classloading}
        at net.silentchaos512.gems.lib.soul.Soul$Events.onServerAboutToStart(Soul.java:195) [?:3.4.7+80] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_95_Events_onServerAboutToStart_FMLServerStartingEvent.invoke(.dynamic) [?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:89) [?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:241) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}

**Comment by SmellyModder** [comment]
Commit 851bb657d82475a6569f0f68c0913cc8cd0914e0 fixes this issue

**Comment by SmellyModder** [comment]
Fixed in the latest version now https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic/files/2848789
